// LOCALHOST
### Get all moviess
GET http://localhost:3000/moviess


### Get movies by id
GET http://localhost:3000/moviess/65b2d7ebfcfd43ef693a1ba2


### Create movies
POST http://localhost:3000/moviess HTTP/1.1
content-type: application/json

{
    "firstName":"Ashley",
    "lastName":"Weaver",
    "email":"aWeaver@test.com",
    "favoriteColor":"Brown",
    "birthday":"06/19/2000"
}


### PUT movies
PUT http://localhost:3000/moviess/65b2d7fdfcfd43ef693a1ba4 HTTP/1.1
content-type: application/json

{
    "firstName":"Sarah",
    "lastName":"Birch",
    "email":"test@gmail.com",
    "favoriteColor":"Green",
    "birthday":"12/12/20"
}
### DELETE movies
DELETE http://localhost:3000/moviess/65b2d8b3fcfd43ef693a1bae HTTP/1.1

// PRODUCTION Deploy
### Get all moviess
GET https://cse341-instructor.herokuapp.com/moviess


### Get movies by id
GET https://cse341-instructor.herokuapp.com/moviess/622023f642f9ab4cd6e060b3


### Create movies
POST https://cse341-instructor.herokuapp.com/moviess HTTP/1.1
content-type: application/json

{
    "firstName":"Ashley",
    "lastName":"Weaver",
    "email":"aWeaver@test.com",
    "favoriteColor":"Brown",
    "birthday":"06/19/2000"
}


### PUT movies
PUT https://cse341-instructor.herokuapp.com/moviess/6220bcb39cd507e920c75a0b HTTP/1.1
content-type: application/json

{
    "firstName":"Sarah",
    "lastName":"Birch",
    "email":"sarahB@gmail.com",
    "favoriteColor":"Yellow",
    "birthday":"06/12/20"
}


### DELETE movies
DELETE https://cse341-instructor.herokuapp.com/moviess/6220e34083149913680f9a64 HTTP/1.1