// LOCALHOST
### Get all moviess
GET http://localhost:3000/movies


### Get movies by id
GET http://localhost:3000/movies/65b2d7ebfcfd43ef693a1ba2


### Create movies
POST http://localhost:3000/movies HTTP/1.1
content-type: application/json

{
    "nombre":"El sexto sentido",
    "director":"M. Night Shyamala",
    "clasificacion":"Drama"   
}


### PUT movies
PUT http://localhost:3000/movies/65b2d7fdfcfd43ef693a1ba4 HTTP/1.1
content-type: application/json

{
    "nombre":"Todo Sobre Mi Madre",
    "director":"Almodobar",
    "clasificacion":"Drama"
}

### DELETE movies
DELETE http://localhost:3000/movies/65b2d84ffcfd43ef693a1ba8 HTTP/1.1

// PRODUCTION Deploy
### Get all moviess

GET http://localhost:3000/movies


### Get movies by id
GET http://localhost:3000/movies/65b2d7ebfcfd43ef693a1ba2


### Create movies
POST http://localhost:3000/movies HTTP/1.1
content-type: application/json

{
    "nombre":"El sexto sentido",
    "director":"M. Night Shyamala",
    "clasificacion":"Drama",
   
}


### PUT movies
PUT http://localhost:3000/movies/65b2d7fdfcfd43ef693a1ba4 HTTP/1.1
content-type: application/json

{
    "nombre":"Todo Sobre Mi Madre",
    "director":"Almodobar",
    "clasificacion":"Drama"
}
### DELETE movies
DELETE http://localhost:3000/movies/65b2d84ffcfd43ef693a1ba8 HTTP/1.1