// LOCALHOST
### Get all moviess
GET https://w03-individual-project.onrender.com/movies


### Get movies by id
GET https://w03-individual-project.onrender.com/movies/65b2d7ebfcfd43ef693a1ba2


### Create movies
POST https://w03-individual-project.onrender.com/movies HTTP/1.1
content-type: application/json

{
    "nombre":"El sexto sentido",
    "director":"M. Night Shyamala",
    "clasificacion":"Drama"   
}


### PUT movies
PUT https://w03-individual-project.onrender.com/movies/65b2d7fdfcfd43ef693a1ba4 HTTP/1.1
content-type: application/json

{
    "nombre":"Todo Sobre Mi Madre",
    "director":"Almodobar",
    "clasificacion":"Drama"
}

### DELETE movies
DELETE https://w03-individual-project.onrender.com/movies/65b2d84ffcfd43ef693a1ba8 HTTP/1.1

// PRODUCTION Deploy
### Get all moviess

GET https://w03-individual-project.onrender.com/movies


### Get movies by id
GET https://w03-individual-project.onrender.com/movies/65b2d7ebfcfd43ef693a1ba2


### Create movies
POST https://w03-individual-project.onrender.com/movies HTTP/1.1
content-type: application/json

{
    "nombre":"El sexto sentido",
    "director":"M. Night Shyamala",
    "clasificacion":"Drama",
   
}


### PUT movies
PUT https://w03-individual-project.onrender.com/movies/65b2d7fdfcfd43ef693a1ba4 HTTP/1.1
content-type: application/json

{
    "nombre":"Todo Sobre Mi Madre",
    "director":"Almodobar",
    "clasificacion":"Drama"
}
### DELETE movies
DELETE https://w03-individual-project.onrender.com/movies/65b2d84ffcfd43ef693a1ba8 HTTP/1.1